### ISSUE TITLE
Properly validate Warning and Critical

### ISSUE THREAD

**Issue by ricardomaraschini** [ricardomaraschini/oomhero#4]
We need to check if Warning and Critical are properly set. Rules are very simple:

1. Warning and Critical must be lower or equal to 100;
2. Warning must be lower or equal to Critical;

If conditions are not met, use the default values and notify through log.

**Comment by vdepatla** [comment]
@ricardomaraschini created this PR https://github.com/ricardomaraschini/oomhero/pull/9 for the change .. this is my first doing a PR on github let me know if something is missing or not linked ..

**Comment by ricardomaraschini** [comment]
Thanks for your PR @vdepatla, wish you all the best. You did good!
